### ISSUE TITLE
A Defi Token (DEFI) token issuance and redemption smart contract

### ISSUE THREAD

**Issue by TT1943** [gojoychain/mining-contract#8]
User deposits 1 JUSD will receive 1 Defi Token (DEFI), lock 0.95 JUSD in smart contract, and send 0.05 JUSD to creator.
User deposit 1 DEFI will receive 0.95 JUSD.

**Comment by dwalintukan** [comment]
done in separate repo
https://github.com/gojoychain/DEFI-token
